This file focuses on supercon2. Purpose is to organize and clean the database

In [17]:
import numpy as np
import pandas as pd  #to read and work with .csv files
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv('supercon2_v22.12.03.csv')                           #to read the .csv file and store it in a dataframe called df
data = pd.read_csv('supercon2_v22.12.03.csv', header=0)

data.head(10)

,id,rawMaterial,materialId,name,formula,doping,shape,materialClass,fabrication,substrate,...,appliedPressure,section,subsection,hash,title,doi,authors,publisher,journal,year
0,61ba959a7c13e4f711c50c3e,InO x films,1.942078e+09,NaN,InO x,NaN,films,Oxides,NaN,NaN,...,NaN,body,figure,b7d13f231a,Infinite-randomness fixed point of the quantum...,10.1103/physrevb.99.054515,"Nicholas A Lewellyn, Ilana M Percher, J J Nels...",American Physical Society (APS),Physical Review B,2019.0
1,61ba959a0cb3d3a5e6c50c3e,"x = 0.04, 0.05, and 0.06)",1.064204e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,body,paragraph,67f5567e75,Tuning the interplay between nematicity and sp...,10.1038/s41467-018-04471-7,"S-H Baek, Dilip Bhoi, Woohyun Nam, Bumsung Lee...",Springer Science and Business Media LLC,Nature Communications,2018.0
2,61ba959a720b8b3d36c50c3e,amorphous In-O films,-1.411819e+09,NaN,In-O,NaN,films,Alloys,NaN,NaN,...,NaN,body,NaN,e74ca47303,Scaling analysis of the magnetic field-tuned q...,10.1134/1.568304,"V F Gantmakher, M V Golubkov, V T Dolgopolov, ...",Pleiades Publishing Ltd,Journal of Experimental and Theoretical Physic...,1998.0
3,61ba959a6a35f302ddc50c3e,x= 0.108,4.969883e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,body,figure,c8fb7503bc,Doping evolution of antiferromagnetism and tra...,NaN,"Rui Zhang, Dongliang Gong, Xingye Lu, Shiliang...",NaN,NaN,2015.0
4,61ba959a85b12ae79ac50c3e,PrRu 2 Si 2,-5.030707e+08,NaN,PrRu 2 Si 2,NaN,NaN,Alloys,NaN,NaN,...,NaN,header,abstract,e8285dd0b7,Crystal-field interactions in PrRu2Si2,10.1088/0953-8984/12/34/307,"R Michalski, Z Ropka, R J Radwanski",IOP Publishing,Journal of Physics: Condensed Matter,2014.0
5,61ba959a05e6aa6710c50c3e,Lu3Os4Ge13,1.093100e+09,NaN,Lu3Os4Ge13,NaN,NaN,Alloys,NaN,NaN,...,NaN,header,abstract,96a5aef3c7,Superconductivity in Y 3 Ru 4 Ge 13 and Lu 3 O...,NaN,"Om Prakash, A Thamizhavel, S Ramakrishnan",NaN,NaN,2014.0
6,61ba959ba01e2beb09c50c3e,LaMnO 3.04,-7.810355e+08,NaN,LaMnO 3.04,NaN,NaN,Oxides,NaN,NaN,...,NaN,body,paragraph,21ea47f3a7,Ultraslow Polaron Dynamics in Low-Doped Mangan...,10.1103/physrevlett.87.127206,"G Allodi, M Cestelli Guidi, R De Renzi, A Cane...",American Physical Society (APS),Physical Review Letters,2014.0
7,61ba959ba01e2beb09c50c3f,doping con- centrations 0.06 < x ≤ 0.1,-6.308684e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,body,paragraph,21ea47f3a7,Ultraslow Polaron Dynamics in Low-Doped Mangan...,10.1103/physrevlett.87.127206,"G Allodi, M Cestelli Guidi, R De Renzi, A Cane...",American Physical Society (APS),Physical Review Letters,2014.0
8,61ba959ba01e2beb09c50c40,La 0.8 Ca 0.2 MnO 3.015,-2.625461e+08,NaN,La 0.8 Ca 0.2 MnO 3.015,NaN,NaN,Oxides,NaN,NaN,...,NaN,body,paragraph,21ea47f3a7,Ultraslow Polaron Dynamics in Low-Doped Mangan...,10.1103/physrevlett.87.127206,"G Allodi, M Cestelli Guidi, R De Renzi, A Cane...",American Physical Society (APS),Physical Review Letters,2014.0
9,61ba959ba01e2beb09c50c41,LaMnO 3.06,6.122870e+07,NaN,LaMnO 3.06,NaN,NaN,Oxides,NaN,NaN,...,NaN,body,figure,21ea47f3a7,Ultraslow Polaron Dynamics in Low-Doped Mangan...,10.1103/physrevlett.87.127206,"G Allodi, M Cestelli Guidi, R De Renzi, A Cane...",American Physical Society (APS),Physical Review Letters,2014.0

Step 1: get rid of NAN values in appliedPressure row and ambient variations

In [19]:
print(data.columns)                #print the column names of the dataframe to understand the structure of the data

data_clean = data.dropna(subset=['appliedPressure'])             #to remove rows with missing values in the 'appliedPressure' column, remove NaN

# See unique pressure values
#print(data_clean['appliedPressure'].unique())

# Remove ambient variations
data_clean = data_clean[
    ~data_clean['appliedPressure'].astype(str)
    .str.contains('ambient', case=False, na=False)
]


data_clean = data_clean[                                     #Keep only rows that contain a number
    data_clean['appliedPressure'].astype(str)
    .str.contains(r'\d', na=False)
]




valid_units = r'GPa|kbar|MPa|bar|atm|Torr|torr' 

data_clean = data_clean[                                  #keep only rows that contain a unit
    data_clean['appliedPressure'].astype(str)
    .str.contains(valid_units, case=False, na=False)
]

print(data_clean['appliedPressure'].unique()[:])

Index(['id', 'rawMaterial', 'materialId', 'name', 'formula', 'doping', 'shape',
       'materialClass', 'fabrication', 'substrate', 'variables',
       'criticalTemperature', 'criticalTemperatureMeasurementMethod',
       'appliedPressure', 'section', 'subsection', 'hash', 'title', 'doi',
       'authors', 'publisher', 'journal', 'year'],
      dtype='object')
['9 GPa' '2-6 GPa' '7 kbar' '460 GPa' '1 GPa' '5.4 GPa' '2.5 GPa' '20 GPa'
 '150 GPa' '190 GPa' '15 GPa' '25 kbar' '1.48 GPa' '2.6 GPa' '20-30 GPa'
 '0.97GPa pressure' '1GPa' '1.68GPa' '0.35GPa' '0GPa' '1.5GPa' '0.55GPa'
 '1.92 GPa' '6 GPa' '32−35 GPa' '8−10 GPa' '120 GPa' '300 GPa' '18 GPa'
 '5 GPa' '125 GPa' '2.0 GPa' '1.8 and 2.0 GPa' '10 GPa' '8.9 GPa'
 '0.5 GPa' '5kbar' '40-60kbar' '10 GPa pressure' '17 kbar' '11 and 13 GPa'
 '2 GPa' '200 GPa' '155 GPa' '207 GPa' '96 GPa' '250 GPa' '21.5 GPa'
 '3 GPa' '16 GPa' '6 kbar' '17.5, 11, and 14 kbar' '4 GPa' '7.5GPa'
 '40 GPa' '0.7 GPa' '2 × 10 −2 mbar' '2.7 GPa' '210 GPa' '285 GPa'
 '170 GPa' '267 GPa' '9.0 GPa' '6.7 GPa' '5.5 GPa' '∼170 GPa' '1.86 GPa'
 '179 GPa' '130 GPa' '≈ 150GPa' '7-9 GPa' '160 GPa' '2.8 GPa' '13.5 GPa'
 '8 GPa' '15 kbar' '0.8 GPa' '3.5 kbar' '3.2 GPa' '89 GPa' '33 GPa'
 '157 GPa' '0.3 GPa' '4.0 GPa' '175 GPa' '137 − 218 GPa' '166 − 237 GPa'
 '4-5 GPa' '2.35 GPa' '27 GPa' '7.0 GPa' '3×10 −11 torr' '1.2 GPa'
 '12 kbar' '3.5 and 4.8 GPa' '350 GPa' '100 GPa' '70- 80 kbar' '30 GPa'
 '165 GPa' '0 GPa' '31 GPa' '4-6 GPa' '3.7GPa' '20 to 24 GPa' '48 GPa'
 '20.3 GPa' '11.0 GPa' '400-500 GPa' '9.65 GPa' '6.32 GPa' '5.22 GPa'
 '4.15 GPa' '6.23 GPa' '9 and 30 GPa' '6.16 GPa' '0 kbar'
 '0.3 kbar pressure' '18 kbar' '40 kbar' '1.5 GPa' '4.2 GPa' '4.25 GPa'
 '8.2 GPa' '400 GPa' '5 kbar' '20 kbar' '12.5 GPa' '3GPa' '1.63 GPa'
 '160-200 GPa' '177 GPa' '3.5 GPa' '1.18 GPa' '3.0 GPa' '7-8 GPa'
 '1.22 GPa' '32 kbar' '30 kbar 37' '35 kbar' '3-5 GPa' '16 kbar' '270 GPa'
 '10.8 kbar' '1 GPa pressure' '78.5 GPa' '75.7 GPa' '5.7 GPa' '93 GPa'
 '140 GPa' '150 GPa pressure' '10-12 GPa' '4 GPa pressure' '46.6 GPa'
 '1.6 GPa' '16.8 GPa' '14.4 GPa' '25 mbar' '12.4 GPa' '500 GPa' '~100 GPa'
 '50-60 GPa' '0-30 GPa' '7 GPa' '1.5 kbar' '25.3kbar' '6.5 Kbar' '5.0 GPa'
 '5.1×10 −3 , 6.4×10 −3 , and 2.5×10 −3 GPa' '133 GPa' '12 GPa' '2.43 GPa'
 '2.65 GPa' '50 GPa' '12.8 GPa' '23.5 GPa' '8.5 GPa' '1.3 GPa' '10.5 GPa'
 '1 × 10 −8 mbar' '43 GPa' '20 Mbar' '100 mTorr' '16kbar' '15 mbar'
 '0.002 atm' '23.8 GPa' '3.31 GPa' '0.9, 1.5 and 2.05 GPa'
 '0.7 GPa pressure' '25GPa' '2.37 GPa' '15-30 GPa' '1.75 GPa' '8GPa'
 '7GPa' '1.48GPa' '100-250 GPa' '3.5GPa' '17.8 kbar' '120 kbar' '94 GPa'
 '2.76 MPa' '310, 000 atm' '450 GPa' '5.8 kbar' '4.5 GPa' '240 GPa'
 '11 GPa'
 '30 years ago, however, Wittig [14] demonstrated that at pressures above 7 GPa'
 '21 GPa' '14 GPa' '1.7 GPa' '2 to 2.5 GPa' '0.48 GPa' '0.82 GPa'
 '30 kbar' '2.4 GPa' '54 atm' '320 kbar' '180 GPa' '113 GPa' '500GPa'
 '9.3 GPa' '0.54 GPa' '83 GPa' '9 kbar' '5 kbar pressures' '7.6 GPa'
 '13.9 GPa' '172 GPa' '11,5 GPa' '30 GPa pressure' '∼ 16 kbar' '55 kbar'
 '52.5 GPa' '7.8 GPa' '8.5 kbar' '11.8 and 20.8 kbar' '2.19GPa' '38 GPa'
 '36kbar' '196 MPa' '45 kbar' '40-GPa' '20 GPa ≤P≤ 40 GPa' '9.4 GPa'
 '1.5 and 6.5 GPa' '55% up to 4 GPa' '1.09 GPa' '300 atm' '63.2 GPa'
 '2.5GPa' '1~2 GPa' '5.6 GPa' '2.60 GPa' '0.39 GPa' '0.80 GPa' '10.4 GPa'
 '0.3kbar' '4.8 GPa' '0.55 GPa and T > 1130' '0.5Torr' '13.6 GPa'
 '0,59 GPa' '2.1 GPa' '0.91 GPa' '1.97GPa' '2GPa' '0.9 GPa'
 '9 % with 0.9 GPa' '19GPa' '5.0 -5.5 GPa' '0.8 mbar' '0.94 GPa'
 '25-60 GPa' '90 GPa' '110 GPa' '0.4 and 2.3 GPa' '1.8 and 2.5 GPa'
 '16 kbar pressure' '1.0 and 1.5 GPa' '2.61 GPa' '10 to 17 GPa' '6−9 GPa'
 '360 GPa' '275 GPa' '1.41 GPa' '1.17 GPa' '10 -2 mbar' '2.80 GPa'
 '65 GPa' '4.94 GPa' '81 GPa' '89 kbar' '10 -8 Torr' '36 GPa' '45 GPa'
 '100 GPa and 250 GPa' '6-8GPa' '0.05 GPa' '1.85 GPa' '115 GPa'
 '1.4 GPa pressure' '6.1 GPa' '1.4 MPa' '2.3 GPa' '8.9 GPa pressure'
 '1.15 GPa' '2.75 GPa' '0.69 GPa' '0.79 GPa' '90 kbar' '100 kbar' '0kbar'
 '0.29 GPa' '3.1 GPa' '10.5 kbar' '0.22 GPa' '7 − 9 GPa' '28 kbar'
 '1.74 GPa' 'applied pressure 1.74 GPa' '4- 5.5 GPa' '120kbar' '40kbar'
 '0.75 GPa' '4.1 GPa' '170-190 GPa' '182 ± 8 GPa' '0.35 to 0.86 GPa'
 '3 GPa pressure' '160 Gpa' '7.5 GPa' '2.8 GPa pressure'
 '0.4 GPa pressure' '0.95 GPa' '180 and 200 GPa' '5GPa' '0.2 kbar'
 '9.5 GPa' '280 GPa' '43.5 GPa' '70.8 GPa' '44 GPa' '4.4 GPa' '60-150 GPa'
 '0.3 kbar' '0.4 GPa' '1.5 GPa pressure' '0.63 GPa' '∼ 210 GPa' '2.55 GPa'
 '13 GPa' '100-200 GPa' '17.7 GPa' '25- 30 GPa' '24 GPa' '29 GPa' '7kbar'
 '11.5 GPa' '166 GPa' '8.9 Gpa' '5×10 −11 Torr' '3 ÷ 4) GPa'
 '4 x 10 −11 torr' '3.9 GPa' '182 GPa' '10 kbar' '6 Gpa' '70 GPa'
 '1-22 GPa' '6.5 GPa' '202 GPa' '0.48 Gpa' '160 GPa pressure' '15 kbar 13'
 '60 mTorr' '55.5 mTorr' '98.5 kbar' '414 GPa' '539 GPa' '5 × 10 −11 Torr'
 '4.5GPa' '170-180 GPa' '60 GPa' '71 GPa' '10-22 GPa' '57 GPa' '32 GPa'
 '38GPa pressure' '1.0 GPa -49 GPa' '0.7 GPa -41.2 GPa'
 '1.5 GPa -36.2 GPa' '20GPa' '3 ∼ 4 GPa pressure' '1 atm' '2.36 GPa'
 '31.7 GPa' '220 GPa' '201 GPa' '45 and 4 kbar' '112 GPa' '400 atm'
 '11 to 20 GPa' '110 kbar' '0.6 GPa' '69 GPa' '6.5 kbar' '3 kbar'
 '1.8 to 2.1 GPa' '2.2 GPa' '1.5 to 1.8 GPa' '8 kbar' '11 -15 GPa'
 '23 GPa' '2.32 GPa' '1.28 GPa' '2-3 GPa' '10 -9 mbar' '12.7 kbar'
 '265 kbar' '84 GPa' '1.31 GPa' '0 to 1.4 GPa' '1.46 GPa' '35 GPa'
 '∼155 GPa' '1.9 GPa' '1 to 1.6 GPa' '0.7 MPa' '7 GPa and 12 GPa'
 '27.4 GPa' '3.0 -4.5 GPa' '0.06 GPa' '162 GPa' '0.8GPa' '14kbar'
 '2.1 atm' '9.98 kbar' '22 GPa' '89 GPa pressure' '0.7GPa' '150 Gpa'
 '100GPa' '4 -6 GPa' '14.8 GPa' '3.8 GPa' '3 atmospheres' '160 kbar'
 '10 mTorr' '20kbar' '100-230 GPa' '0.56 GPa' '0.01 mbar' '11 and 12 GPa'
 '13 kbar' '8.2GPa' '0.2 GPa' '1 bar' '192 GPa' '160∼200 GPa' '6.0 GPa'
 '0.55 GPa' '0.1 MPa' '200 MPa pressure' '7 kbar pressure' '52.8 GPa'
 '1 × 10 −10 Torr' '48.9 GPa' '≃0.4−0.5 GPa' '.5GPa' '.5 GPa'
 '0GPa pressure' '26.5 kbar' '2.47 GPa' '1.27 GPa' '3.38 GPa' '30GPa'
 '30 GPa pres' '6-17 GPa' '8.5kbar' '9.5kbar' '1.00 GPa' '0.73 GPa'
 '450 MPa' '30 MPa' '0.1GPa' '0.76 GPa' '50 kbar' '3×10 -10 Torr'
 '166 -237 GPa' '40 -60 kbar' '10 −10 mbar' '12.2 and 16.0 GPa'
 '2 and 4 GPa' '15 to 25 GPa' '9 and 12 GPa']

step 2: convert these pressures to the same units (GPa of Kbar)

In [20]:
import re

#This functiontakes one cell from the appliedPressure column and returns a number in GPa
def convert_to_gpa(text):
    t = str(text).lower()                              #Convert to string and lowercase for easier processing
    numbers = re.findall(r'\d+(?:\.\d+)?', t)           #Extract the first number (integer or decimal) from the text
    if not numbers:
        return np.nan
    value = float(numbers[0])                             #take the first number found and convert it to a float (at least for now), may change it later

    if 'gpa' in t:
        return value
    elif 'kbar' in t:
        return value * 0.1
    elif 'mpa' in t:
        return value * 0.001
    elif 'atm' in t:
        return value * 0.000101325
    elif 'torr' in t:
        return value * 1.33322e-7
    elif 'bar' in t:
        return value * 1e-4
    else:
        return np.nan

data_clean['pressure_GPa'] = data_clean['appliedPressure'].apply(convert_to_gpa)

# Remove anything that failed conversion
data_clean = data_clean.dropna(subset=['pressure_GPa'])                   #created a new column called 'pressure_GPa' by applying the convert_to_gpa function to the 'appliedPressure' column, and then removed any rows where the conversion failed (i.e., where 'pressure_GPa' is NaN)

print(data_clean[['appliedPressure', 'pressure_GPa']])

                                         appliedPressure  pressure_GPa
45                                                 9 GPa  9.000000e+00
118                                              2-6 GPa  2.000000e+00
154                                               7 kbar  7.000000e-01
215                                              460 GPa  4.600000e+02
264                                                1 GPa  1.000000e+00
267                                                1 GPa  1.000000e+00
355                                              5.4 GPa  5.400000e+00
357                                              2.5 GPa  2.500000e+00
358                                               20 GPa  2.000000e+01
359                                               20 GPa  2.000000e+01
378                                              150 GPa  1.500000e+02
379                                              190 GPa  1.900000e+02
482                                               15 GPa  1.500000e+01
503                                              25 kbar  2.500000e+00
526                                             1.48 GPa  1.480000e+00
561                                              2.6 GPa  2.600000e+00
660                                            20-30 GPa  2.000000e+01
682                                     0.97GPa pressure  9.700000e-01
683                                                 1GPa  1.000000e+00
684                                              1.68GPa  1.680000e+00
687                                              0.35GPa  3.500000e-01
688                                              0.35GPa  3.500000e-01
689                                                 0GPa  0.000000e+00
690                                              0.35GPa  3.500000e-01
691                                     0.97GPa pressure  9.700000e-01
692                                               1.5GPa  1.500000e+00
696                                              0.55GPa  5.500000e-01
697                                             1.92 GPa  1.920000e+00
698                                              0.55GPa  5.500000e-01
699                                              0.35GPa  3.500000e-01
735                                                6 GPa  6.000000e+00
745                                                6 GPa  6.000000e+00
747                                            32−35 GPa  3.200000e+01
752                                             8−10 GPa  8.000000e+00
813                                              190 GPa  1.900000e+02
814                                              120 GPa  1.200000e+02
815                                              300 GPa  3.000000e+02
816                                               18 GPa  1.800000e+01
819                                              120 GPa  1.200000e+02
945                                                5 GPa  5.000000e+00
993                                              125 GPa  1.250000e+02
1001                                             2.0 GPa  2.000000e+00
1003                                     1.8 and 2.0 GPa  1.800000e+00
1023                                              10 GPa  1.000000e+01
1121                                             8.9 GPa  8.900000e+00
1125                                             0.5 GPa  5.000000e-01
1138                                             150 GPa  1.500000e+02
1169                                               5kbar  5.000000e-01
1170                                           40-60kbar  4.000000e+00
1227                                     10 GPa pressure  1.000000e+01
1335                                             17 kbar  1.700000e+00
1366                                       11 and 13 GPa  1.100000e+01
1472                                               9 GPa  9.000000e+00
1476                                               2 GPa  2.000000e+00
1564                                             200 GPa  2.000000e+02
1566                                             200 GPa  2.000000e+02
1567                                             155 GPa  1.550000e+02
1568                                             207 GPa  2.070000e+02
1569                                             155 GPa  1.550000e+02
1570                                             200 GPa  2.000000e+02
1571                                              96 GPa  9.600000e+01
1573                                             250 GPa  2.500000e+02
1574                                             200 GPa  2.000000e+02
1575                                             200 GPa  2.000000e+02
1702                                            21.5 GPa  2.150000e+01
1722                                               3 GPa  3.000000e+00
1724                                              16 GPa  1.600000e+01
1765                                              6 kbar  6.000000e-01
1840                               17.5, 11, and 14 kbar  1.750000e+00
1872                                             250 GPa  2.500000e+02
1900                                               4 GPa  4.000000e+00
1903                                             150 GPa  1.500000e+02
1963                                              7.5GPa  7.500000e+00
2091                                               6 GPa  6.000000e+00
2128                                             250 GPa  2.500000e+02
2140                                              40 GPa  4.000000e+01
2142                                              40 GPa  4.000000e+01
2148                                              40 GPa  4.000000e+01
2184                                             0.7 GPa  7.000000e-01
2332                                      2 × 10 −2 mbar  2.000000e-04
2345                                             2.6 GPa  2.600000e+00
2352                                             2.7 GPa  2.700000e+00
2353                                               3 GPa  3.000000e+00
2385                                             210 GPa  2.100000e+02
2386                                             210 GPa  2.100000e+02
2387                                             285 GPa  2.850000e+02
2390                                             170 GPa  1.700000e+02
2392                                             250 GPa  2.500000e+02
2394                                             267 GPa  2.670000e+02
2509                                             9.0 GPa  9.000000e+00
2510                                             6.7 GPa  6.700000e+00
2531                                             5.5 GPa  5.500000e+00
2538                                               4 GPa  4.000000e+00
2540                                            ∼170 GPa  1.700000e+02
2597                                               3 GPa  3.000000e+00
2644                                             155 GPa  1.550000e+02
2711                                               2 GPa  2.000000e+00
2713                                            1.86 GPa  1.860000e+00
2715                                               2 GPa  2.000000e+00
2772                                             179 GPa  1.790000e+02
2782                                             130 GPa  1.300000e+02
2785                                             120 GPa  1.200000e+02
2786                                            ≈ 150GPa  1.500000e+02
2803                                             210 GPa  2.100000e+02
2815                                             200 GPa  2.000000e+02
2817                                             250 GPa  2.500000e+02
2820                                             207 GPa  2.070000e+02
2821                                             200 GPa  2.000000e+02
2869                                             7-9 GPa  7.000000e+00
2870                                             7-9 GPa  7.000000e+00
3010                                             155 GPa  1.550000e+02
3012                                             160 GPa  1.600000e+02
3047                                             2.8 GPa  2.800000e+00
3129                                            13.5 GPa  1.350000e+01
3198                                               8 GPa  8.000000e+00
3349                                             15 kbar  1.500000e+00
3449                                             0.8 GPa  8.000000e-01
3468                                              15 GPa  1.500000e+01
3484                                              20 GPa  2.000000e+01
3559                                             8.9 GPa  8.900000e+00
3618                                               8 GPa  8.000000e+00
3656                                            3.5 kbar  3.500000e-01
3657                                             3.2 GPa  3.200000e+00
3663                                             2.6 GPa  2.600000e+00
3704                                              89 GPa  8.900000e+01
3705                                              33 GPa  3.300000e+01
3707                                             157 GPa  1.570000e+02
3711                                               5 GPa  5.000000e+00
3713                                             0.3 GPa  3.000000e-01
3757                                             4.0 GPa  4.000000e+00
3784                                             175 GPa  1.750000e+02
3785                                       137 − 218 GPa  1.370000e+02
3786                                             150 GPa  1.500000e+02
3787                                       166 − 237 GPa  1.660000e+02
3877                                             2.5 GPa  2.500000e+00
4038                                            1.48 GPa  1.480000e+00
4053                                             4-5 GPa  4.000000e+00
4067                                            2.35 GPa  2.350000e+00
4134                                              27 GPa  2.700000e+01
4152                                             7.0 GPa  7.000000e+00
4153                                            ∼170 GPa  1.700000e+02
4173                                              20 GPa  2.000000e+01
4187                                       3×10 −11 torr  3.999660e-07
4199                                             1.2 GPa  1.200000e+00
4229                                               5 GPa  5.000000e+00
4332                                             15 kbar  1.500000e+00
4342                                             12 kbar  1.200000e+00
4346                                               2 GPa  2.000000e+00
4426                                     3.5 and 4.8 GPa  3.500000e+00
4427                                              10 GPa  1.000000e+01
4428                                               5 GPa  5.000000e+00
4429                                               3 GPa  3.000000e+00
4464                                             350 GPa  3.500000e+02
4466                                             350 GPa  3.500000e+02
4471                                             150 GPa  1.500000e+02
4472                                             200 GPa  2.000000e+02
4473                                             100 GPa  1.000000e+02
4474                                             150 GPa  1.500000e+02
4543                                             170 GPa  1.700000e+02
4545                                             100 GPa  1.000000e+02
4555                                         70- 80 kbar  7.000000e+00
4589                                              30 GPa  3.000000e+01
4592                                             165 GPa  1.650000e+02
4594                                             200 GPa  2.000000e+02
4595                                               0 GPa  0.000000e+00
4596                                               0 GPa  0.000000e+00
4597                                              96 GPa  9.600000e+01
4600                                              31 GPa  3.100000e+01
4652                                             0.5 GPa  5.000000e-01
4787                                             250 GPa  2.500000e+02
4788                                             250 GPa  2.500000e+02
4795                                             250 GPa  2.500000e+02
4824                                             4-6 GPa  4.000000e+00
4841                                               2 GPa  2.000000e+00
4845                                               3 GPa  3.000000e+00
5025                                               4 GPa  4.000000e+00
5086                                              3.7GPa  3.700000e+00
5092                                        20 to 24 GPa  2.000000e+01
5093                                              48 GPa  4.800000e+01
5095                                            20.3 GPa  2.030000e+01
5125                                            11.0 GPa  1.100000e+01
5173                                             170 GPa  1.700000e+02
5287                                            1.48 GPa  1.480000e+00
5379                                             200 GPa  2.000000e+02
5380                                             250 GPa  2.500000e+02
5385                                         400-500 GPa  4.000000e+02
5434                                              20 GPa  2.000000e+01
5435                                              20 GPa  2.000000e+01
5459                                            9.65 GPa  9.650000e+00
5460                                            6.32 GPa  6.320000e+00
5462                                            5.22 GPa  5.220000e+00
5463                                               0 GPa  0.000000e+00
5464                                            4.15 GPa  4.150000e+00
5465                                            6.23 GPa  6.230000e+00
5469                                             155 GPa  1.550000e+02
5470                                        9 and 30 GPa  9.000000e+00
5471                                            6.16 GPa  6.160000e+00
5472                                            4.15 GPa  4.150000e+00
5473                                               6 GPa  6.000000e+00
5523                                               5 GPa  5.000000e+00
5539                                              0 kbar  0.000000e+00
5564                                              30 GPa  3.000000e+01
5624                                   0.3 kbar pressure  3.000000e-02
5627                                             12 kbar  1.200000e+00
5628                                             8.9 GPa  8.900000e+00
5694                                             18 kbar  1.800000e+00
5695                                             40 kbar  4.000000e+00
5754                                             17 kbar  1.700000e+00
5832                                               8 GPa  8.000000e+00
5934                                              10 GPa  1.000000e+01
5946                                             4.0 GPa  4.000000e+00
5978                                               4 GPa  4.000000e+00
5983                                             1.5 GPa  1.500000e+00
6004                                             4.2 GPa  4.200000e+00
6111                                            4.25 GPa  4.250000e+00
6179                                               8 GPa  8.000000e+00
6180                                               8 GPa  8.000000e+00
6181                                             8.2 GPa  8.200000e+00
6247                                             400 GPa  4.000000e+02
6248                                             120 GPa  1.200000e+02
6249                                             300 GPa  3.000000e+02
6250                                             155 GPa  1.550000e+02
6251                                             150 GPa  1.500000e+02
6252                                             160 GPa  1.600000e+02
6253                                             200 GPa  2.000000e+02
6254                                             210 GPa  2.100000e+02
6258                                              5 kbar  5.000000e-01
6259                                             20 kbar  2.000000e+00
6270                                              20 GPa  2.000000e+01
6304                                             160 GPa  1.600000e+02
6327                                            12.5 GPa  1.250000e+01
6476                                               3 GPa  3.000000e+00
6480                                               3 GPa  3.000000e+00
6494                                                3GPa  3.000000e+00
6625                                             20 kbar  2.000000e+00
6626                                              5 kbar  5.000000e-01
6641                                              30 GPa  3.000000e+01
6643                                            1.63 GPa  1.630000e+00
6741                                             200 GPa  2.000000e+02
6742                                         160-200 GPa  1.600000e+02
6772                                            1.48 GPa  1.480000e+00
6820                                             150 GPa  1.500000e+02
6821                                             150 GPa  1.500000e+02
6822                                             200 GPa  2.000000e+02
6865                                            1.63 GPa  1.630000e+00
6946                                             200 GPa  2.000000e+02
6948                                             200 GPa  2.000000e+02
6949                                             200 GPa  2.000000e+02
6956                                             1.5 GPa  1.500000e+00
6966                                             177 GPa  1.770000e+02
7029                                               4 GPa  4.000000e+00
7031                                               3 GPa  3.000000e+00
7033                                               3 GPa  3.000000e+00
7034                                             3.5 GPa  3.500000e+00
7037                                               1 GPa  1.000000e+00
7038                                               1 GPa  1.000000e+00
7039                                            1.18 GPa  1.180000e+00
7042                                               3 GPa  3.000000e+00
7043                                             3.0 GPa  3.000000e+00
7045                                               3 GPa  3.000000e+00
7123                                             7-8 GPa  7.000000e+00
7162                                             8.9 GPa  8.900000e+00
7237                                            1.22 GPa  1.220000e+00
7249                                             32 kbar  3.200000e+00
7250                                          30 kbar 37  3.000000e+00
7251                                             35 kbar  3.500000e+00
7262                                             3-5 GPa  3.000000e+00
7426                                             16 kbar  1.600000e+00
7462                                             8.9 GPa  8.900000e+00
7502                                             200 GPa  2.000000e+02
7505                                             270 GPa  2.700000e+02
7508                                             270 GPa  2.700000e+02
7509                                             200 GPa  2.000000e+02
7510                                             155 GPa  1.550000e+02
7511                                             150 GPa  1.500000e+02
7512                                           10.8 kbar  1.080000e+00
7533                                      1 GPa pressure  1.000000e+00
7534                                             2.8 GPa  2.800000e+00
7552                                            78.5 GPa  7.850000e+01
7555                                            78.5 GPa  7.850000e+01

Printing results

In [21]:
pd.set_option('display.max_rows', None)
print(data_clean.loc[:, ['appliedPressure', 'pressure_GPa']])

                                         appliedPressure  pressure_GPa
45                                                 9 GPa  9.000000e+00
118                                              2-6 GPa  2.000000e+00
154                                               7 kbar  7.000000e-01
215                                              460 GPa  4.600000e+02
264                                                1 GPa  1.000000e+00
267                                                1 GPa  1.000000e+00
355                                              5.4 GPa  5.400000e+00
357                                              2.5 GPa  2.500000e+00
358                                               20 GPa  2.000000e+01
359                                               20 GPa  2.000000e+01
378                                              150 GPa  1.500000e+02
379                                              190 GPa  1.900000e+02
482                                               15 GPa  1.500000e+01
503                                              25 kbar  2.500000e+00
526                                             1.48 GPa  1.480000e+00
561                                              2.6 GPa  2.600000e+00
660                                            20-30 GPa  2.000000e+01
682                                     0.97GPa pressure  9.700000e-01
683                                                 1GPa  1.000000e+00
684                                              1.68GPa  1.680000e+00
687                                              0.35GPa  3.500000e-01
688                                              0.35GPa  3.500000e-01
689                                                 0GPa  0.000000e+00
690                                              0.35GPa  3.500000e-01
691                                     0.97GPa pressure  9.700000e-01
692                                               1.5GPa  1.500000e+00
696                                              0.55GPa  5.500000e-01
697                                             1.92 GPa  1.920000e+00
698                                              0.55GPa  5.500000e-01
699                                              0.35GPa  3.500000e-01
735                                                6 GPa  6.000000e+00
745                                                6 GPa  6.000000e+00
747                                            32−35 GPa  3.200000e+01
752                                             8−10 GPa  8.000000e+00
813                                              190 GPa  1.900000e+02
814                                              120 GPa  1.200000e+02
815                                              300 GPa  3.000000e+02
816                                               18 GPa  1.800000e+01
819                                              120 GPa  1.200000e+02
945                                                5 GPa  5.000000e+00
993                                              125 GPa  1.250000e+02
1001                                             2.0 GPa  2.000000e+00
1003                                     1.8 and 2.0 GPa  1.800000e+00
1023                                              10 GPa  1.000000e+01
1121                                             8.9 GPa  8.900000e+00
1125                                             0.5 GPa  5.000000e-01
1138                                             150 GPa  1.500000e+02
1169                                               5kbar  5.000000e-01
1170                                           40-60kbar  4.000000e+00
1227                                     10 GPa pressure  1.000000e+01
1335                                             17 kbar  1.700000e+00
1366                                       11 and 13 GPa  1.100000e+01
1472                                               9 GPa  9.000000e+00
1476                                               2 GPa  2.000000e+00
1564                                             200 GPa  2.000000e+02
1566                                             200 GPa  2.000000e+02
1567                                             155 GPa  1.550000e+02
1568                                             207 GPa  2.070000e+02
1569                                             155 GPa  1.550000e+02
1570                                             200 GPa  2.000000e+02
1571                                              96 GPa  9.600000e+01
1573                                             250 GPa  2.500000e+02
1574                                             200 GPa  2.000000e+02
1575                                             200 GPa  2.000000e+02
1702                                            21.5 GPa  2.150000e+01
1722                                               3 GPa  3.000000e+00
1724                                              16 GPa  1.600000e+01
1765                                              6 kbar  6.000000e-01
1840                               17.5, 11, and 14 kbar  1.750000e+00
1872                                             250 GPa  2.500000e+02
1900                                               4 GPa  4.000000e+00
1903                                             150 GPa  1.500000e+02
1963                                              7.5GPa  7.500000e+00
2091                                               6 GPa  6.000000e+00
2128                                             250 GPa  2.500000e+02
2140                                              40 GPa  4.000000e+01
2142                                              40 GPa  4.000000e+01
2148                                              40 GPa  4.000000e+01
2184                                             0.7 GPa  7.000000e-01
2332                                      2 × 10 −2 mbar  2.000000e-04
2345                                             2.6 GPa  2.600000e+00
2352                                             2.7 GPa  2.700000e+00
2353                                               3 GPa  3.000000e+00
2385                                             210 GPa  2.100000e+02
2386                                             210 GPa  2.100000e+02
2387                                             285 GPa  2.850000e+02
2390                                             170 GPa  1.700000e+02
2392                                             250 GPa  2.500000e+02
2394                                             267 GPa  2.670000e+02
2509                                             9.0 GPa  9.000000e+00
2510                                             6.7 GPa  6.700000e+00
2531                                             5.5 GPa  5.500000e+00
2538                                               4 GPa  4.000000e+00
2540                                            ∼170 GPa  1.700000e+02
2597                                               3 GPa  3.000000e+00
2644                                             155 GPa  1.550000e+02
2711                                               2 GPa  2.000000e+00
2713                                            1.86 GPa  1.860000e+00
2715                                               2 GPa  2.000000e+00
2772                                             179 GPa  1.790000e+02
2782                                             130 GPa  1.300000e+02
2785                                             120 GPa  1.200000e+02
2786                                            ≈ 150GPa  1.500000e+02
2803                                             210 GPa  2.100000e+02
2815                                             200 GPa  2.000000e+02
2817                                             250 GPa  2.500000e+02
2820                                             207 GPa  2.070000e+02
2821                                             200 GPa  2.000000e+02
2869                                             7-9 GPa  7.000000e+00
2870                                             7-9 GPa  7.000000e+00
3010                                             155 GPa  1.550000e+02
3012                                             160 GPa  1.600000e+02
3047                                             2.8 GPa  2.800000e+00
3129                                            13.5 GPa  1.350000e+01
3198                                               8 GPa  8.000000e+00
3349                                             15 kbar  1.500000e+00
3449                                             0.8 GPa  8.000000e-01
3468                                              15 GPa  1.500000e+01
3484                                              20 GPa  2.000000e+01
3559                                             8.9 GPa  8.900000e+00
3618                                               8 GPa  8.000000e+00
3656                                            3.5 kbar  3.500000e-01
3657                                             3.2 GPa  3.200000e+00
3663                                             2.6 GPa  2.600000e+00
3704                                              89 GPa  8.900000e+01
3705                                              33 GPa  3.300000e+01
3707                                             157 GPa  1.570000e+02
3711                                               5 GPa  5.000000e+00
3713                                             0.3 GPa  3.000000e-01
3757                                             4.0 GPa  4.000000e+00
3784                                             175 GPa  1.750000e+02
3785                                       137 − 218 GPa  1.370000e+02
3786                                             150 GPa  1.500000e+02
3787                                       166 − 237 GPa  1.660000e+02
3877                                             2.5 GPa  2.500000e+00
4038                                            1.48 GPa  1.480000e+00
4053                                             4-5 GPa  4.000000e+00
4067                                            2.35 GPa  2.350000e+00
4134                                              27 GPa  2.700000e+01
4152                                             7.0 GPa  7.000000e+00
4153                                            ∼170 GPa  1.700000e+02
4173                                              20 GPa  2.000000e+01
4187                                       3×10 −11 torr  3.999660e-07
4199                                             1.2 GPa  1.200000e+00
4229                                               5 GPa  5.000000e+00
4332                                             15 kbar  1.500000e+00
4342                                             12 kbar  1.200000e+00
4346                                               2 GPa  2.000000e+00
4426                                     3.5 and 4.8 GPa  3.500000e+00
4427                                              10 GPa  1.000000e+01
4428                                               5 GPa  5.000000e+00
4429                                               3 GPa  3.000000e+00
4464                                             350 GPa  3.500000e+02
4466                                             350 GPa  3.500000e+02
4471                                             150 GPa  1.500000e+02
4472                                             200 GPa  2.000000e+02
4473                                             100 GPa  1.000000e+02
4474                                             150 GPa  1.500000e+02
4543                                             170 GPa  1.700000e+02
4545                                             100 GPa  1.000000e+02
4555                                         70- 80 kbar  7.000000e+00
4589                                              30 GPa  3.000000e+01
4592                                             165 GPa  1.650000e+02
4594                                             200 GPa  2.000000e+02
4595                                               0 GPa  0.000000e+00
4596                                               0 GPa  0.000000e+00
4597                                              96 GPa  9.600000e+01
4600                                              31 GPa  3.100000e+01
4652                                             0.5 GPa  5.000000e-01
4787                                             250 GPa  2.500000e+02
4788                                             250 GPa  2.500000e+02
4795                                             250 GPa  2.500000e+02
4824                                             4-6 GPa  4.000000e+00
4841                                               2 GPa  2.000000e+00
4845                                               3 GPa  3.000000e+00
5025                                               4 GPa  4.000000e+00
5086                                              3.7GPa  3.700000e+00
5092                                        20 to 24 GPa  2.000000e+01
5093                                              48 GPa  4.800000e+01
5095                                            20.3 GPa  2.030000e+01
5125                                            11.0 GPa  1.100000e+01
5173                                             170 GPa  1.700000e+02
5287                                            1.48 GPa  1.480000e+00
5379                                             200 GPa  2.000000e+02
5380                                             250 GPa  2.500000e+02
5385                                         400-500 GPa  4.000000e+02
5434                                              20 GPa  2.000000e+01
5435                                              20 GPa  2.000000e+01
5459                                            9.65 GPa  9.650000e+00
5460                                            6.32 GPa  6.320000e+00
5462                                            5.22 GPa  5.220000e+00
5463                                               0 GPa  0.000000e+00
5464                                            4.15 GPa  4.150000e+00
5465                                            6.23 GPa  6.230000e+00
5469                                             155 GPa  1.550000e+02
5470                                        9 and 30 GPa  9.000000e+00
5471                                            6.16 GPa  6.160000e+00
5472                                            4.15 GPa  4.150000e+00
5473                                               6 GPa  6.000000e+00
5523                                               5 GPa  5.000000e+00
5539                                              0 kbar  0.000000e+00
5564                                              30 GPa  3.000000e+01
5624                                   0.3 kbar pressure  3.000000e-02
5627                                             12 kbar  1.200000e+00
5628                                             8.9 GPa  8.900000e+00
5694                                             18 kbar  1.800000e+00
5695                                             40 kbar  4.000000e+00
5754                                             17 kbar  1.700000e+00
5832                                               8 GPa  8.000000e+00
5934                                              10 GPa  1.000000e+01
5946                                             4.0 GPa  4.000000e+00
5978                                               4 GPa  4.000000e+00
5983                                             1.5 GPa  1.500000e+00
6004                                             4.2 GPa  4.200000e+00
6111                                            4.25 GPa  4.250000e+00
6179                                               8 GPa  8.000000e+00
6180                                               8 GPa  8.000000e+00
6181                                             8.2 GPa  8.200000e+00
6247                                             400 GPa  4.000000e+02
6248                                             120 GPa  1.200000e+02
6249                                             300 GPa  3.000000e+02
6250                                             155 GPa  1.550000e+02
6251                                             150 GPa  1.500000e+02
6252                                             160 GPa  1.600000e+02
6253                                             200 GPa  2.000000e+02
6254                                             210 GPa  2.100000e+02
6258                                              5 kbar  5.000000e-01
6259                                             20 kbar  2.000000e+00
6270                                              20 GPa  2.000000e+01
6304                                             160 GPa  1.600000e+02
6327                                            12.5 GPa  1.250000e+01
6476                                               3 GPa  3.000000e+00
6480                                               3 GPa  3.000000e+00
6494                                                3GPa  3.000000e+00
6625                                             20 kbar  2.000000e+00
6626                                              5 kbar  5.000000e-01
6641                                              30 GPa  3.000000e+01
6643                                            1.63 GPa  1.630000e+00
6741                                             200 GPa  2.000000e+02
6742                                         160-200 GPa  1.600000e+02
6772                                            1.48 GPa  1.480000e+00
6820                                             150 GPa  1.500000e+02
6821                                             150 GPa  1.500000e+02
6822                                             200 GPa  2.000000e+02
6865                                            1.63 GPa  1.630000e+00
6946                                             200 GPa  2.000000e+02
6948                                             200 GPa  2.000000e+02
6949                                             200 GPa  2.000000e+02
6956                                             1.5 GPa  1.500000e+00
6966                                             177 GPa  1.770000e+02
7029                                               4 GPa  4.000000e+00
7031                                               3 GPa  3.000000e+00
7033                                               3 GPa  3.000000e+00
7034                                             3.5 GPa  3.500000e+00
7037                                               1 GPa  1.000000e+00
7038                                               1 GPa  1.000000e+00
7039                                            1.18 GPa  1.180000e+00
7042                                               3 GPa  3.000000e+00
7043                                             3.0 GPa  3.000000e+00
7045                                               3 GPa  3.000000e+00
7123                                             7-8 GPa  7.000000e+00
7162                                             8.9 GPa  8.900000e+00
7237                                            1.22 GPa  1.220000e+00
7249                                             32 kbar  3.200000e+00
7250                                          30 kbar 37  3.000000e+00
7251                                             35 kbar  3.500000e+00
7262                                             3-5 GPa  3.000000e+00
7426                                             16 kbar  1.600000e+00
7462                                             8.9 GPa  8.900000e+00
7502                                             200 GPa  2.000000e+02
7505                                             270 GPa  2.700000e+02
7508                                             270 GPa  2.700000e+02
7509                                             200 GPa  2.000000e+02
7510                                             155 GPa  1.550000e+02
7511                                             150 GPa  1.500000e+02
7512                                           10.8 kbar  1.080000e+00
7533                                      1 GPa pressure  1.000000e+00
7534                                             2.8 GPa  2.800000e+00
7552                                            78.5 GPa  7.850000e+01
7555                                            78.5 GPa  7.850000e+01

In [31]:
#data_clean[['id', 'rawMaterial', 'materialId','formula', 'materialClass', 'variables', 'appliedPressure', 'pressure_GPa', 'criticalTemperature']]      #uncomment this line to see all rows of the cleaned dataframe with the specified columns, including the new 'pressure_GPa' column
data_clean[['id', 'rawMaterial', 'materialId','formula', 'materialClass', 'variables', 'appliedPressure', 'pressure_GPa', 'criticalTemperature']].head(50)

,id,rawMaterial,materialId,formula,materialClass,variables,appliedPressure,pressure_GPa,criticalTemperature
45,61ba959de4552e90a8c50c43,FeSe 1−x,-1.050844e+09,FeSe 1−x,"Iron-chalcogenides, Chalcogenides",NaN,9 GPa,9.00,37 K
118,61ba95a185fc223534c50c43,BaFe 2 As 2,-4.731701e+08,BaFe 2 As 2,"Iron-pnictides, Pnictides",NaN,2-6 GPa,2.00,28 K
154,61ba95a45cc438644dc50c43,Cs 3 C 60,3.105467e+08,Cs 3 C 60,Carbides,NaN,7 kbar,0.70,38 K
215,61ba95aa783c1e8128c50c53,metallic hydrogen,4.990380e+07,NaN,NaN,NaN,460 GPa,460.00,234 K
264,61ba95ae783c1e8128c50c56,BaNi 2 P 2 single crystals,-2.531872e+08,BaNi 2 P 2,Pnictides,NaN,1 GPa,1.00,3 K
267,61ba95ae783c1e8128c50c59,BaNi 2 P 2,1.734361e+09,BaNi 2 P 2,Pnictides,NaN,1 GPa,1.00,3 K
355,61ba95b514d91e0862c50c56,CeCoGe 3,-7.490919e+08,CeCoGe 3,Alloys,NaN,5.4 GPa,5.40,0.7 K
357,61ba95b514d91e0862c50c58,CeIrSi 3,-4.382956e+07,CeIrSi 3,Alloys,NaN,2.5 GPa,2.50,1.6 K
358,61ba95b514d91e0862c50c59,CeIrGe 3,8.464833e+08,CeIrGe 3,Alloys,NaN,20 GPa,20.00,1.5 K
359,61ba95b514d91e0862c50c5a,CeIrGe3,9.612450e+07,CeIrGe3,Alloys,NaN,20 GPa,20.00,1.5 K
378,61ba95b6720b8b3d36c50c54,sulfur hydride H 3 S,1.076822e+09,H3S,NaN,NaN,150 GPa,150.00,203 K
379,61ba95b6720b8b3d36c50c55,La hydride LaH 10±x (x < 1),-1.374339e+09,LaH 10±x,Alloys,x=< 1,190 GPa,190.00,260 K
482,61ba95bd85fc223534c50c54,6 Li ( 7 Li),-1.639731e+09,6 Li ( 7 Li,Alloys,NaN,15 GPa,15.00,11.2 K
503,61ba95c17f36ec6458c50c55,EuFe 2 As 2,5.166741e+08,EuFe 2 As 2,"Iron-pnictides, Pnictides",NaN,25 kbar,2.50,30 K
526,61ba95c25cc438644dc50c5b,FeSe,1.427175e+09,FeSe,"Iron-chalcogenides, Chalcogenides",NaN,1.48 GPa,1.48,27 K
561,61ba95c87f36ec6458c50c58,CeIrSi 3,9.095382e+07,CeIrSi 3,Alloys,NaN,2.6 GPa,2.60,1.6 K
660,61ba95d2ab9e3e9324c50c58,HgBa 2 Ca 2 Cu 3 O 8+δ (Hg-1223),-4.884440e+08,HgBa 2 Ca 2 Cu 3 O 8+δ,Alloys,NaN,20-30 GPa,20.00,160 K
682,61ba95d456f16aed29c50c58,CeO 0.5 F 0.5 BiS 2,-1.922335e+09,CeO 0.5 F 0.5 BiS 2,"Chalcogenides, Oxides, Fluorides",NaN,0.97GPa pressure,0.97,7K
683,61ba95d456f16aed29c50c59,"Sr 0.5 RE 0.5 FBiS 2 (RE=Ce, Nd, Pr and Sm)",-1.349907e+09,Sr 0.5 RE 0.5 FBiS 2,"Chalcogenides, Fluorides","RE=Ce, Nd, Pr, Sm",1GPa,1.00,10K
684,61ba95d456f16aed29c50c5a,NdO 0.5 F 0.5 BiS 2,2.169895e+08,NdO 0.5 F 0.5 BiS 2,"Chalcogenides, Oxides, Fluorides",NaN,1.68GPa,1.68,6.2K
687,61ba95d456f16aed29c50c5d,Sr 0.5 Pr 0.5 FBiS 2,1.431732e+09,Sr 0.5 Pr 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,0.35GPa,0.35,2K
688,61ba95d456f16aed29c50c5e,Sr 0.5 La 0.5 FBiS 2,2.026476e+09,Sr 0.5 La 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,0.35GPa,0.35,2K
689,61ba95d456f16aed29c50c5f,Sr 0.5 La 0.5 FBiS 2,2.051493e+09,Sr 0.5 La 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,0GPa,0.00,2.3K
690,61ba95d456f16aed29c50c60,LaO 0.5 F 0.5 BiS 2,-1.936294e+09,LaO 0.5 F 0.5 BiS 2,"Chalcogenides, Oxides, Fluorides",NaN,0.35GPa,0.35,2.5K
691,61ba95d456f16aed29c50c61,Sr 0.5 Sm 0.5 FBiS 2,1.894803e+07,Sr 0.5 Sm 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,0.97GPa pressure,0.97,2.2K
692,61ba95d456f16aed29c50c62,Sr 0.5 Nd 0.5 FBiS 2,2.080539e+09,Sr 0.5 Nd 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,1.5GPa,1.50,9K
696,61ba95d456f16aed29c50c66,LaO 0.5 F 0.5 BiS 2,-1.997900e+09,LaO 0.5 F 0.5 BiS 2,"Chalcogenides, Oxides, Fluorides",NaN,0.55GPa,0.55,5K
697,61ba95d456f16aed29c50c67,LaO 0.5 F 0.5 BiS 2,-1.354837e+09,LaO 0.5 F 0.5 BiS 2,"Chalcogenides, Oxides, Fluorides",NaN,1.92 GPa,1.92,10K
698,61ba95d456f16aed29c50c68,Sr 0.5 Ce 0.5 FBiS 2,-1.348816e+09,Sr 0.5 Ce 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,0.55GPa,0.55,9.4K
699,61ba95d456f16aed29c50c69,Sr 0.5 Sm 0.5 FBiS 2,1.124596e+07,Sr 0.5 Sm 0.5 FBiS 2,"Chalcogenides, Fluorides",NaN,0.35GPa,0.35,2.4K
735,61ba95d71b93c0c6bec50c75,NdFeAsO 0.82 Fe 0.18,6.852456e+08,NdFeAsO 0.82 Fe 0.18,"Iron-pnictides, Oxides, Pnictides",NaN,6 GPa,6.00,51 K
745,61ba95d93af0453d0cc50c67,SmFeAsO 1-x F x,2.087718e+09,SmFeAsO 1-x F x,"Iron-pnictides, Pnictides, Oxides, Fluorides",NaN,6 GPa,6.00,55 K
747,61ba95da14d91e0862c50c6c,Tellurium (Te),-9.738173e+08,NaN,NaN,NaN,32−35 GPa,32.00,2.5 to 7.4 K
752,61ba95da14d91e0862c50c71,graphite intercalated com- pound CaC 6,-5.321196e+08,CaC 6,Carbides,NaN,8−10 GPa,8.00,11.5 to 15.1 K
813,61ba95de20fc3eae4bc50c6b,LaH 10,1.233823e+09,LaH 10,"Hydrides, Alloys",NaN,190 GPa,190.00,265 K
814,61ba95de20fc3eae4bc50c6c,YH 6,-9.331106e+08,YH 6,"Hydrides, Alloys",NaN,120 GPa,120.00,264 K
815,61ba95de20fc3eae4bc50c6d,YH6,-7.290824e+08,YH6,"Hydrides, Alloys",NaN,300 GPa,300.00,290 K
816,61ba95de20fc3eae4bc50c6e,YH 3 crystal,1.040024e+09,YH 3,"Hydrides, Alloys",NaN,18 GPa,18.00,40 K
819,61ba95de20fc3eae4bc50c71,YH 6,-9.311928e+08,YH 6,"Hydrides, Alloys",NaN,120 GPa,120.00,260 K
945,61ba95e9c2c99830dec50c6f,CaNiBN,-1.951011e+09,CaNiBN,"Nitrides, Borides",NaN,5 GPa,5.00,4.1 K
993,61ba95eb6a35f302ddc50c6e,AlH 3,1.723366e+09,AlH 3,"Hydrides, Alloys",NaN,125 GPa,125.00,7 K
1001,61ba95eb5cc438644dc50c72,CeRhIn5,5.650704e+08,CeRhIn5,Alloys,NaN,2.0 GPa,2.00,2.0 K
1003,61ba95eb5cc438644dc50c74,CeRhIn 5,-1.027208e+09,CeRhIn 5,Alloys,NaN,1.8 and 2.0 GPa,1.80,2 K
1023,61ba95ec1b5bc7b48bc50c84,AxFe2-ySe2,5.809403e+08,AxFe2-ySe2,"Iron-chalcogenides, Chalcogenides",NaN,10 GPa,10.00,48.7 K
1121,61ba95f21b93c0c6bec50c8d,FeSe,1.400216e+09,FeSe,"Iron-chalcogenides, Chalcogenides",NaN,8.9 GPa,8.90,36.7 K
1125,61ba95f25ad933a7cac50c73,BaBi 3 single crystal,1.475573e+09,BaBi 3,Alloys,NaN,0.5 GPa,0.50,6.6 K
1138,61ba95f37f36ec6458c50c73,H 3 S,-1.916787e+08,H 3 S,"Hydrides, Chalcogenides",NaN,150 GPa,150.00,203 K
1169,61ba95f6e4dc5fe1bac50c7d,CaFe2As2,-1.684978e+09,CaFe2As2,"Iron-pnictides, Pnictides",NaN,5kbar,0.50,10K
1170,61ba95f6e4dc5fe1bac50c7e,SrFe2As2,-1.710038e+09,SrFe2As2,"Iron-pnictides, Pnictides",NaN,40-60kbar,4.00,38K
1227,61ba95f805e6aa6710c50c76,R = Tb,1.300462e+09,NaN,NaN,R=Tb,10 GPa pressure,10.00,51 K